---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  A base VPC for tests

Resources:

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub ${CidrPrefix}.${CidrNull}/${CidrMask}
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: StockTesting

  SsmVpcId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TestingVpcId
      Description: VPC ID for stock testing VPC
      Type: String
      Value: !Ref Vpc

  SsmVpcCidr:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TestingVpcCidr
      Description: VPC CIDR for stock testing VPC
      Type: StringList
      Value: !Join
        - ','
        - - !Ref CidrPrefix
          - !Ref CidrNull
          - !Ref CidrMask

  PublicSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.12.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public0
      VpcId: !Ref Vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.12.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public1
      VpcId: !Ref Vpc

  SsmPublicSubnets:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TestingVpcPublicSubnets
      Description: Public subnets for stock testing VPC
      Type: StringList
      Value: !Join
        - ','
        - - !Ref PublicSubnet0
          - !Ref PublicSubnet1

  PublicRoutetable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: PublicRoute

  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: publicigw

  IgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Igw
      VpcId: !Ref Vpc

  PublicRouteDefault:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRoutetable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Igw

  RouteTableAssoc0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRoutetable
      SubnetId: !Ref PublicSubnet0

  RouteTableAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRoutetable
      SubnetId: !Ref PublicSubnet1

  PrivateZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneTags:
        - Key: VpcId
          Value: !Ref Vpc
      Name: !Ref VpcZoneName
      VPCs:
        - VPCId: !Ref Vpc
          VPCRegion: us-east-1

  SsmZoneInfo:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TestingVpcZoneInfo
      Description: Hosted Zone ID and name for stock testing VPC
      Type: StringList
      Value: !Join
        - ','
        - - !Ref PrivateZone
          - !Ref VpcZoneName

Parameters:
  StackName:
    Type: String
  CidrPrefix:
    Type: String
    Default: 10.12
  CidrNull:
    Type: String
    Default: 0.0
  CidrMask:
    Type: String
    Default: 16
  VpcZoneName:
    Type: String
    Default: jniedrauer.local
