---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Kinesis Stream and a test EC2 instance

Resources:

  CommandStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: TestCommandStream
      ShardCount: 1

  InstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AllowSSH
      GroupDescription: Allow SSH for admins
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: !Ref AdminCidr
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref VpcId

  KclRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: KclRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/kinesis-test/'
      Policies:
        - PolicyName: KinesisConsumer
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'kinesis:DescribeStream'
                  - 'kinesis:GetRecords'
                  - 'kinesis:GetShardIterator'
                Resource:
                  - '*'
        - PolicyName: KinesisConsumerLogging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource:
                  - '*'

  KclInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: KclRole
    Properties:
      Path: '/kinesis-test/'
      Roles:
        - KclRole

  KclInstance0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${CfnBucket}/${StackName}/ec2.yml'
      Parameters:
        Name: KinesisClient0
        Group: KclServers
        Ami: ami-428aa838
        SecurityGroup: !Ref InstanceSg
        IamInstanceProfile: !Ref KclInstanceProfile
        Subnet: !Select
          - 0
          - !Ref PublicSubnets
        CfnBucket: !Ref CfnBucket

Parameters:
  AdminCidr:
    Type: AWS::SSM::Parameter::Value<String>
    Default: AdminCidr
    NoEcho: true
  CfnBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CfnBucket
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TestingVpcId
  PublicSubnets:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: TestingVpcPublicSubnets
  StackName:
    Type: String
