---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Task Runner and a test EC2 instance

Resources:

  InstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AllowSSH
      GroupDescription: Allow SSH for admins
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: !Ref AdminCidr
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: Name
          Value: TaskRunnerTestServers
      VpcId: !Ref VpcId

  TaskRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TaskRunnerRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/data-pipeline/'
      Policies:
        - PolicyName: DataPipelineShit
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'datapipeline:*'
                Resource:
                  - '*'

  TaskRunnerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: TaskRunnerRole
    Properties:
      Path: '/data-pipelines/'
      Roles:
        - TaskRunnerRole

  DataPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${CfnBucket}/${StackName}/pipeline.yml'

  TaskRunnerInstance0:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataPipeline
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${CfnBucket}/${StackName}/ec2.yml'
      Parameters:
        Name: TaskRunner0
        Group: TaskRunners
        WorkerGroup: wg-0000
        Ami: ami-428aa838
        SecurityGroup: !Ref InstanceSg
        IamInstanceProfile: !Ref TaskRunnerInstanceProfile
        Subnet: !Select
          - 0
          - !Ref PublicSubnets
        CfnBucket: !Ref CfnBucket

  TaskRunnerInstance1:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataPipeline
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${CfnBucket}/${StackName}/ec2.yml'
      Parameters:
        Name: TaskRunner1
        Group: TaskRunners
        WorkerGroup: wg-0001
        Ami: ami-428aa838
        SecurityGroup: !Ref InstanceSg
        IamInstanceProfile: !Ref TaskRunnerInstanceProfile
        Subnet: !Select
          - 1
          - !Ref PublicSubnets
        CfnBucket: !Ref CfnBucket

Parameters:
  AdminCidr:
    Type: AWS::SSM::Parameter::Value<String>
    Default: AdminCidr
    NoEcho: true
  CfnBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CfnBucket
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TestingVpcId
  PublicSubnets:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: TestingVpcPublicSubnets
  StackName:
    Type: String
