---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Task Runner and a test EC2 instance

Resources:

  InstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AllowSSH
      GroupDescription: Allow SSH for admins
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: !Ref AdminCidr
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: Name
          Value: TaskRunnerTestServers
      VpcId: !Ref VpcId

  TaskRunnerInstance0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${CfnBucket}/${StackName}/ec2.yml'
      Parameters:
        Name: TaskRunner0
        Group: TaskRunners
        Ami: ami-428aa838
        SecurityGroup: !Ref InstanceSg
        Subnet: !Select
          - 0
          - !Ref PublicSubnets
        CfnBucket: !Ref CfnBucket

Parameters:
  AdminCidr:
    Type: AWS::SSM::Parameter::Value<String>
    Default: AdminCidr
    NoEcho: true
  CfnBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CfnBucket
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TestingVpcId
  PublicSubnets:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: TestingVpcPublicSubnets
  StackName:
    Type: String
