---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Data Pipelines

Resources:

  DataPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - datapipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/data-pipeline/'
      Policies:
        - PolicyName: DataPipelineShit
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'datapipeline:*'
                Resource:
                  - '*'

  Ec2ExecuteCmdsPipeline:
    Type: AWS::DataPipeline::Pipeline
    Properties:
      Name: Ec2ExecuteCmds
      Description: Execute commands on EC2
      Activate: true
      PipelineObjects:
        - Id: Default
          Name: Default
          Fields:
            - Key: type
              StringValue: Default
            - Key: failureAndRerunMode
              StringValue: CASCADE
            - Key: role
              StringValue: !Ref DataPipelineRole
            - Key: scheduleType
              StringValue: ondemand
        - Id: ShellCommandActivityExecutor0
          Name: Process tasks on wg-0000
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: workerGroup
              StringValue: wg-0000
            - Key: command
              StringValue: echo $(date) #{myInputCommand} >>/var/log/task-runner/test.log
        - Id: ShellCommandActivityExecutor1
          Name: Process tasks on wg-0001
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: workerGroup
              StringValue: wg-0001
            - Key: command
              StringValue: echo foo1 >>/var/log/task-runner/test.log
        - Id: ShellCommandActivityExecutor2
          Name: Process tasks on wg-0002
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: workerGroup
              StringValue: wg-0002
            - Key: command
              StringValue: echo foo2 >>/var/log/task-runner/test.log
        - Id: ShellCommandActivityExecutor3
          Name: Process tasks on wg-0003
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: workerGroup
              StringValue: wg-0003
            - Key: command
              StringValue: echo foo3 >>/var/log/task-runner/test.log
