---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Data Pipelines

Resources:

  DataPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - datapipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/data-pipeline/'
      Policies:
        - PolicyName: DataPipelineShit
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'datapipeline:*'
                Resource:
                  - '*'

  Ec2ExecuteCmdsPipeline:
    Type: AWS::DataPipeline::Pipeline
    Properties:
      Name: Ec2ExecuteCmds
      Description: Execute commands on EC2
      Activate: true
      ParameterObjects:
        - Id: myCommandInput
          Attributes:
            - Key: type
              StringValue: String
      ParameterValues:
        - Id: myCommandInput
          StringValue: NOTSET
      PipelineObjects:
        - Id: Default
          Name: Default
          Fields:
            - Key: type
              StringValue: Default
            - Key: failureAndRerunMode
              StringValue: CASCADE
            - Key: role
              StringValue: !Ref DataPipelineRole
            - Key: scheduleType
              StringValue: ondemand
            - Key: maxActiveInstances
              StringValue: 10
        - Id: ShellCommandActivityExecutor0
          Name: Process tasks on wg-0000
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: workerGroup
              StringValue: wg-0000
            - Key: command
              StringValue: echo "$(date) foo0 $1" >>/var/log/task-runner/test.log
            - Key: scriptArgument
              StringValue: "#{myCommandInput}"
