---
# AWS static configuration
region: us-east-1
ec2_keypair: jniedrauer

public_hosted_zone: jniedrauer.com
public_hosted_zone_id: ZELCDUNSF35JN
internal_hosted_zone: jniedrauer.internal
cidr: 10.5.0.0/16
nat_gws: 0
