---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Shared infrastructure for Cloudformation

Resources:

  CfnS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  CfnBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CfnBucket
      Description: Cloudformation shared bucket
      Type: String
      Value: !Ref CfnS3Bucket

  Ec2ProvisionIamUser:
    Type: AWS::IAM::User
    Properties:
      Path: "/automation/"
      Policies:
        - PolicyName: GetS3ProvisioningScripts
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${BucketName}/provisioners/*"
      UserName: !Ref Ec2ProvisionUser

  Ec2ProvisionIamUserKeypair:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      UserName: !Ref Ec2ProvisionIamUser

  Ec2ProvisionIamKeypair:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Ec2ProvisionIamKeypair
      Description: !Sub "IAM API Keys for ${Ec2ProvisionUser}"
      Type: StringList
      Value: !Join
        - ','
        - - !Ref Ec2ProvisionIamUserKeypair
          - !GetAtt Ec2ProvisionIamUserKeypair.SecretAccessKey

Parameters:
  BucketName:
    Type: String
    Default: jniedrauer-cfn-infrastructure
  Ec2ProvisionUser:
    Type: String
    Default: Ec2Provision
